[package]
name = "CodebaseAsReference4Chatbot"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
clipboard-rs = "0.2.4"
ignore = "0.4.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
